### ISSUE TITLE
Retrace as library with API

### ISSUE THREAD

**Issue by JayFoxRox** [apitrace/apitrace#255]
This is an RFC / Feature Request.

If retrace was a library which had simple functions to control it we could easily implement a lot of features on our own. apitrace could also be integrated somewhat deeper in my toolchain.

I had the idea because I have trouble exporting my vertex buffers from apitrace. Also debugging my GLSL using transform feedback within apitrace is next to impossible because I would have to add code to the stream.
If I had access to the current GL context I could do great things such as integrating the state of my software with a simple shader debugger. I could also easily create GUIs for my specific use cases and possibly implement interfaces to other debugger to add more comments to the output. Things which might not be applicable in qapitrace due to platform and API incompatibilities.

Example:

    int main() {
      apitrace_trace_t* trace = apitrace_load(argv[1], APITRACE_SINGLETHREAD | APITRACE_SINGLEBUFFER); // Load a .tace file and create GL context
      [...]
      unsigned int idx = apitrace_search_call_index(trace, 0, "glDraw*"); // Find next draw call
      if (apitrace_position(trace) > idx) { // If we skipped the call already revert to a clean context [so we can reach it by going forward again]
        apitrace_revert();
      }
      apitrace_play(idx, false); // Play until we reach the draw call, don't break for errors
      apitrace_skip(idx+5); // Skip 5 calls!
      // I could use this space to re-implement a possible bugfix for the 5 calls.
      apitrace_type_t type = apitrace_get_parameter_type(idx, 0);
      if (type == APITRACE_POINTER) {
        void* data = apitrace_get_pointer_parameter(idx,0);
        apitrace_set_pointer_parameter(idx,0,data+4); // Modify argument to call..
      } else {
        char* fn = apitrace_get_function(idx, 0);
        printf("Expected a pointer to first argument of '%s'\n",fn);
        free(fn);
      }
      GLint program;
      glGetIntegerv(GL_CURRENT_PROGRAM, &program); // This would also work now because the application state is recreated
      apitrace_play(-1,true); // Finish playing until we hit an error
      printf("Error in call %d\n",apitrace_position(trace));
    } 

It would be up to the user to make sure that the GL context stays valid.
But I  have code in my application to export meshes and use transform feedback on shaders.
If there was an easy way to move that code away from my application that would be great.
I could use GL DebugMessages to inform an application using the proposed API about metadata and execute more GL commands. I could also re-run my application and test changes in code by replacing chunks of code with my own.

Obviously the API used above is horrible, but it should help to get the idea.

**Comment by jrfonseca** [comment]
Sorry for the delay.  I spent some days pondering about this when you first posted this RFC, but I ended not replying at that time.

Retrace as a library is unpractical due to multi-threading: calls need to happen on different threads, to match the threads they were recorded.  That is, the retrace main loop must be in retrace's control, not user code as the example above. Of course, the API could be changed to have a callback.

But more importantly, the sort of use cases you mention (e.g., export meshes and use transform feedback on shaders), is functionality that should be moved into apitrace itself, so that others app developers can use it without reinventing the wheel over and over again.

Of course, the particular case of exporting meshes is not trivial because GL inspection is not powerful enough to get all the necessary information. But this is fixable, either by leveraging (Khronos)]https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/]/Mesa GLSL compilers, or by specing a new GL extension where applications can provide the needed information while tracing.

In short, I understand that apitrace has limitations, but adding retrace would not only take a considerable amount of time and add complexity to the code, but above all, it would compel apitrace users to scratch just their own itch, rather than biting the bullet and help improving apitrace (ie, scratching everybody's itch.)

That said, I can see some merit in allow users to plug in scripts (e.g, Python) to glretrace, enabling them to customize add new behaviors.  But on the other hand, my experience is apitrace user base is strong in C/C++, but avoids scripting languages like the plague, hence all the effort for those bindings might be a waste of time.  Maybe we could have C/C++ plugins, but then again, might as well just patch apitrace (and hopefully contribute the patch it back.)

So, while I appreciate your feedback, this is something I don't plan to pursue, or recommend others to pursue.
