### ISSUE TITLE
Colour background of GL_KHR_debug calls in QApitrace by interpreting ids as RGB

### ISSUE THREAD

**Issue by inequation** [apitrace/apitrace#256]
I'm porting a codebase from D3D9 to OpenGL which is already instrumented for D3D events. I've taken advantage of the existing instrumentation by using a set of macros:
```
#define D3DPERF_BeginEvent(colour, name)             \
    if (GLEW_KHR_debug && threadOwnsDevice())        \
        glPushDebugGroup(GL_DEBUG_SOURCE_APPLICATION,\
                         (GLuint)colour, -1, name)
#define D3DPERF_EndEvent()					\
    if (GLEW_KHR_debug && threadOwnsDevice())		\
        glPopDebugGroup()
```
As you can see, I'm packing the colours as ids. This is far from a 1:1 mapping for most use cases, but it would be cool to have an option to interpret these ids as colour in the call list.

**Comment by jrfonseca** [comment]
I admit it's not a totally bad idea.  But there are two problems.

First, is that would be non-standard -- applications are free to use whatever IDs they want --, so we'd need to design a way for apps to opt in. We'd also need to add smarts to GUI to handle this (which is not so trivial, because the GUI is pretty much API agnostic -- it doesn't "interpret" the calls.)

Furthermore, even Microsoft itself seems to have abandoned the colors in their replacement APIs for D3DPERF_*:

* https://msdn.microsoft.com/en-US/library/windows/desktop/hh446884.aspx
* https://msdn.microsoft.com/en-us/library/windows/desktop/dn280499.aspx

So I'm afraid it would be too much hassle for the limited benefit.

If somebody was determined to do this I wouldn't refuse the patch, but I have no plan to do it myself.
