### ISSUE TITLE
About iOS support (also Metal)

### ISSUE THREAD

**Issue by oscarbg** [apitrace/apitrace#314]
Hi,
It seems apitrace supports Android and on pull requests we even have retrace support.. and also armv8 seems working..
so question is there is interest to implement apitrace with even retrace support on iOS? 
Also will be interested on Metal support.. 
Some help how if I become interested in trying to do the port would be the easiest way to approach it..
Thanks..

**Comment by jrfonseca** [comment]
> so question is there is interest to implement apitrace with even retrace support on iOS? 

I'm happy to accept patches to support iOS, but I have no direct interest in it at this moment. 

I also don't have any iOS experience so I'm afraid I can't provide much guidance on how to do it..

Apitrace does support Mac OS through Cocoa. I understand that iOS APIs have some similarities with MacOSX so I'd expect it wouldn't be too difficult..

> Also will be interested on Metal support.. 

As long as Metal is exclusive to iOS, I would equally have no direct interesting.(Things would be different if by any chance Metal was supported in MacOS.)  I'm happy to accept patches though.

Eitherway, supporting Metal would be a substantial. That said Apitrace already supports totally different APIs like Direct3D and OpenGL, so at least the infrastructure to add another one is already there.

**Comment by jrfonseca** [comment]
I had forgotten that Apple already provides [good tools for debugging OpenGL ES on iOS](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ToolsOverview/ToolsOverview.html).  I never used them, but from the available documentation it seems to exceed apitrace, both feature- and polish-wise.  So on second though, I actually don't see much point to supporting iOS after all.

@oscarbg, if you skim through the [apitrace issues](https://github.com/apitrace/apitrace/issues) and [wiki](https://github.com/apitrace/apitrace/wiki/ToDo) there are loads of cool improvements that could be done to apitrace, other than supporting a different platform/API just for the sake of it. 

I wouldn't refuse patches supporting this if somebody is committed to implement and maintain it, but because it doesn't look like something worth pursuing I'm closing this for issue now.

**Comment by oscarbg** [comment]
You said: "Things would be different if by any chance Metal was supported in MacOS.)"

so this is enough to gather your interest on working on it?

**Comment by jrfonseca** [comment]
Currently the [Xcode Metal frame capture](https://developer.apple.com/library/mac/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Dev-Technique/Dev-Technique.html#//apple_ref/doc/uid/TP40014221-CH8-DontLinkElementID_3) looks sufficient, if not better in all regards.  And I suspect Apple will keep improving Xcode, addressing any shortcomings it might have.

Because Metal API as is set of Objective C protocols (which are syntactically very different from C++ interfaces/methods), it would require a fair amount of work to apitrace plumbing to support it.  Way more than I initially thought (all Python code to support C++ interfaces needs to be forked and adapted to handle Objective C protocols.)

As I said, if someone else is interested in implementing it I would take patches.  But I'm afraid it still doesn't quite seem to be worth my while..

**Comment by jrfonseca** [comment]
Even the `.trace` format would need revisioning.

This is because in Objective C the thing closest to C++ method name is in fact the first argument.   Take draw primitives, where `drawPrimitives` is both the method and the parameter for the primitive type:

    [renderEncoder drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];

One simple way out would be to duplicate drawPrimitives both as method name and 1st parameter.

An alternative to implement Objective C++ as first class citizen in Apitrace would be to implement (by hand) a bidirectional C++ bridge for Metal protocols.  That is, create pure C++ interfaces that invoke Metal, and create a Metal implementation that invokes this C++ interface.  This would allow to add the spec for the C++ interfaces just as any other C++ interfaces.  The draw back is that  the trace wouldn't look and feel like Metal anymore, as method names and parameters (at least first parameter) would be different.

**Comment by ceebers** [comment]
> This is because in Objective C the thing closest to C++ method name is in fact the first argument.

A more accurate statement would be that all of the parameter names form part of the method name, much as parameter types do in C++.

With the above, the method name would be something like "drawPrimitives:vertexStart:vertexCount:" and the parameters would be (MTLPrimitiveTypeTriangle, 0, 3).

Objective C's dynamic binding also allows some very interesting runtime hackery (eg. method swizzling) which is certainly not advised for a shipping application, but might be useful in your debug scenario.
