### ISSUE TITLE
Installing on Mac gets stuck

### ISSUE THREAD

**Issue by TheAbhiKumar** [apitrace/apitrace#333]
It has been building this for over 40 minutes. I am running OSX Yosemite 10.10.2

```
[ 19%] Building CXX object wrappers/CMakeFiles/cgltrace.dir/cgltrace.cpp.o
```

Do any binaries exist for OS X?

**Comment by jrfonseca** [comment]
@TheAbhiKumar you closed this issue. Was the issue solved or was that unintentional?

Yes, compiling cgltrace can take a long time. But 40min means a bug in compiler (probably clang).

What's the compiler version? (`clang --version`)  Maybe the issue will go away if you upgrade to latest XCode.

Another workaround is to build a Debug build instead of Release.  By passing `-DCMAKE_BUILD_TYPE=Debug` to CMake.

**Comment by TheAbhiKumar** [comment]
My bad, should've updated instead of simply just closing. Yes I let it keep running and it finished building after 45 minutes (shortly after I posted this issue). Not sure why it took so long compared to the other files, but it did finish without any errors.

**Comment by jrfonseca** [comment]
OK. Thanks for the update.

The problem is that we automatically generate C++ code  to trace literally thousands of OpenGL API entrypoints into a single (and quite long C++) file. But each function is not too big, so the compiler shouldn't take that long unless it has some inefficiently coded optimization pass.

Still 45 min is quite a lot... I build it regularly on Mac but never seen it take it that long.

Hopefully this has or will be fixed in a future clang version.
