### ISSUE TITLE
NaN is invalid in JSON (fail to show current state in qapitrace)

### ISSUE THREAD

**Issue by gregory38** [apitrace/apitrace#339]
Trying to dump the state of a trace, I get an "illegal number" error message.

The root cause is NaN (string for json) in the uniform buffer
Here the extract of my glretrace json file (online validator complains on NaN)
```
{
  "uniforms": {
    "GL_VERTEX_SHADER": {
      "TextureScale": [0, 0],
      "VertexOffset": [4.374023, 4.561523],
      "VertexScale": [0.0001220703, 0.0001220703]
    },
    "GL_FRAGMENT_SHADER": {
      "AREF": 0,
      "Af": [0, 0, 0, 0],
      "FogColor": [0, 0, 0],
      "HalfTexel": [0, 0, 0, 0],
      "MinF": [0, 0],
      "MinMax": [0, 0, 0, 0],
      "MskFix": [0, 0, 0, 0],
      "TA": [0, 0],
      "TC_OffsetHack": [-4.173789e+33, NaN, 2.242078e-44, -3.488802e+33],
      "WH": [0, 0, 0, 0]
    },
    "GL_GEOMETRY_SHADER": {}
  }
}
```

It used to work on the past, my guess is that json format wasn't validated in the GUI back then.

**Comment by jrfonseca** [comment]
NaN is non-standard JSON.  But it used to work with QJSON just fine. However this apparently regressed when we switched to the Qt5's built-in JSON parser (which seemed a nice simplification but turned out to cause several unexpected problems, such as issue #323).

Could you try the https://github.com/apitrace/apitrace/tree/ubjson branch? It completely side-steps the problem by using binary format (UBJSON) instead of JSON.

**Comment by gregory38** [comment]
Indeed, it correctly shows nan in the uniform buffer :+1:

**Comment by jrfonseca** [comment]
Great. The branch is now merged.
