### ISSUE TITLE
crash when replay with Windows 8.1 and D3D9

### ISSUE THREAD

**Issue by jxzhuge12** [apitrace/apitrace#361]
This is the trace file: https://drive.google.com/file/d/0B57aO3SU9Bd4ZG1UNlExZmZXbG8/view?usp=sharing
When I replay the trace file, the program would crash.

**Comment by jrfonseca** [comment]
The problem is that these calls are causing buffer overflow:

    726184 IDirect3DSurface9::LockRect(this = 0x30f16720, pLockedRect = &{Pitch = 512, pBits = 0x3af1045c}, pRect = &{left = 127, top = 127, right = 128, bottom = 128}, Flags = 0x0) = D3D_OK
    726185 memcpy(dest = 0x3af1045c, src = blob(512), n = 512)
    726186 IDirect3DSurface9::UnlockRect(this = 0x30f16720) = D3D_OK

The blob in memcpy should be just a few bytes (one pixel), not 512 (the whole scan line.)

The bug is when tracing.  The code in https://github.com/apitrace/apitrace/blob/9653f95f75863870a9e6b1ffad8c0ab48fa3fa4d/helpers/d3dcommonsize.hpp#L178 needs to be updated to use actual BytesPerPixel * Width, similar to what's done for D3D10 in https://github.com/apitrace/apitrace/blob/9653f95f75863870a9e6b1ffad8c0ab48fa3fa4d/helpers/dxgisize.hpp#L207

**Comment by jxzhuge12** [comment]
@jrfonseca Thanks very much!

**Comment by jrfonseca** [comment]
I believe the issue is now fixed.  But you should re-capture traces so that memcpy calls use the right sizes.
