### ISSUE TITLE
GUI: "opaque" and "alpha" as option for surface tab

### ISSUE THREAD

**Issue by JayFoxRox** [apitrace/apitrace#374]
The image viewer has the opaque option. It would be great if the surfaces tab also had an opaque option.
Our application renders the color framebuffer with alpha = 0 most of the time.
Unfortunaly this means that the framebuffer preview in the surfaces tab stays "empty". I first have to double click it to get into the image viewer, then use the "opaque" option to see the current framebuffer content.
If the surface tab would have the opaque option which would toggle opaqueness of the preview images that'd be great. Other people could probably use an alpha option too, so it probably makes sense to add both at once.

**Comment by jrfonseca** [comment]
Yes, I agree it would be a good idea.

I'm afraid I don't have the time -- --, but if anybody ventures a patch I'll happily accept.

It's not a 5min thing, mostly because currently the thumbnails are generated once, and there's quite a bit of plumbing necessary to make them dynamic.  Another solution (potentially even better) would be to not-regenerate the thumbnails at all, but  tell Qt widgets to somehow ignore the alpha.  But I'm not sure how practical it is neither.
