### ISSUE TITLE
Add support for DirectComposition tracing

### ISSUE THREAD

**Issue by jrmuizel** [apitrace/apitrace#377]
On Win8 and up you can use DirectComposite to get surfaces to draw to. It would be nice if apitrace understood this.

**Comment by jrmuizel** [comment]
WIP:
http://people.mozilla.org/~jmuizelaar/dcomposition.patch

**Comment by jrfonseca** [comment]
@jrmuizel, I completed this for the most part.

I was stumbling into a bunch of undocumented interfaces trying to trace Metro applications, and it turns out that by tracing DirectComposition I can avoid many of them.

I looked at your WIP above, but it was lacking several interfaces.  I also grew tired of distilling COM interfaces into Python specs through a bunch of ad-hoc Vim/sed scripts like in the past. So I implemented a script that uses Clang to do that (839a3d8747d329e9fc8d2ae029ae3dd867821d97):

    python specs/scripts/cxx2api.py -Idxsdk/Include dcomp.h dcomptypes.h dcompanimation.h

Next time you need to extend apitrace to more Windows COM interfaces, give it a go.

That said, I think that castxml/pygccxml stands more in the way than helps, and I suspect I might rewrite this using Clang Python bindings directly, as it allows to get more of the AST.  In particular it should allow to get the Microsot SAL annotations and get hints like which params are In/Out, array sizes, etc.


Unfortunately, I'm still stumbling into `IID_ID3D11PartnerDevice` undocumented interface even with [simple demos](https://code.msdn.microsoft.com/windowsdesktop/DCompEffectsD2DSDK-5c91336f), and I don't see how the presents happen.  So I think this still needs some extra work.

Give it a go if you can, and let me know how it goes.
