### ISSUE TITLE
How can I debug a running application?

### ISSUE THREAD

**Issue by LifeH2O** [apitrace/apitrace#388]
I am working on an application in visual studio which uses easyhook to hook some directx calls to game and launch it. How can I debug/trace when debugging/running the application from visual studio?

I can start an application and trace all directX calls with API Trace, but what about an application which is running already or being launched from another application? Or more specifically how to trace API calls of a game which is being debugged by visual studio?

**Comment by jrfonseca** [comment]
> I am working on an application in visual studio which uses easyhook to hook some directx calls to game and launch it. 

easyhook will probably interfere with apitrace hooking...

> what about an application which is running already or being launched from another application?

`inject.exe` is capable of injecting into an exiting process if you invoke it directly (instead of `apitrace trace ...`), hooking all the relevant DLL functions.   But this rarely works: if the application already invoked `D3D11CreateDevice*` then it's too late -- there's no way to wrap the device and all objects created by it.

> Or more specifically how to trace API calls of a game which is being debugged by visual studio?

Why would you want to do that? Use two debugging tools simultanously?

In fact, it's possible to debug and trace simultanouesly by doing

    apitrace trace --debug ...

This will invoke the default JIT debugger (possible Visual Studio or Windbg) to debug the application after it was injected.


BTW, there's no bug reported here.  This sort of open discusion is better handled in the mailing list.
