### ISSUE TITLE
Apitrace crashes with swtor and wine

### ISSUE THREAD

**Issue by EoD** [apitrace/apitrace#397]
I am using wine 1.7.45 and st/nine enabled and I get a crash almost every time I try to use apitrace with [swtor's launcher.exe](https://appdb.winehq.org/objectManager.php?sClass=application&iId=13553).
The backtrace: https://gist.github.com/EoD/cf759116a4af8744bdb7

What I am doing:
```
export WINEDLLOVERRIDES='D:\Downloads\apitrace-msvc\x86\lib\wrappers\d3d9.dll=n'
wine /my_d/Downloads/apitrace-msvc/x86/bin/apitrace.exe trace -a d3d9 launcher.exe
```

I am using the apitrace binaries from http://people.freedesktop.org/~jrfonseca/apitrace/ with both the XP and non-XP msvc-binaries.

**Comment by jrfonseca** [comment]
According to [this](http://locklessinc.com/articles/pthreads_on_windows/) article, section _Critical Sections for Mutexes_

> The trick here is that `InitializeCriticalSection()` is not allowed to fail. It tries to allocate a critical section debug object, but if no memory is available, it sets the pointer to a specific value. (One would expect that value to be `NULL`, but it is actually `(void *)-1` for some reason.) Thus we can use this special value for that pointer, and the critical section code will work.

so one should be able to statically initialize critical sections by doing.

    static CRITICAL_SECTION Mutex = {(PCRITICAL_SECTION_DEBUG)-1, -1, 0, 0, 0, 0};

and that's precisely what apitrace does.

But WINE apparently uses the `NULL` pointer, instead of `-1`, as seen in [here](http://source.winehq.org/git/wine.git/blob/a786dca935c3e9b3d85853db4b61700e590a1c8b:/dlls/ntdll/critsection.c#l323).

I'm going fix this issue in apitrace by using `InitializeCriticalSection` as we should.  I don't remember why I used a static initializer, but there's really no need here.

That said, I wonder if this should be fixed in WINE too.  Or, if the above trick is indeed incorrect.

FWIW, Mesa3D also heavily relies on the above static critical section initializer trick, so it would be nice to get to the bottom of this.

**Comment by jrfonseca** [comment]
One more thing: I also don't understand why this only happens with SWTOR's launcher.  The critical section in question is used all the time, but other apps didn't cause WINE to crash inside `EnterCriticalSection`.

Oh, and for the record, tracing natively (ie, on a real Windows system instead of WINE), did not cause any crash.

**Comment by jrfonseca** [comment]
> One more thing: I also don't understand why this only happens with SWTOR's launcher. 

I understand why: the mutex is timing out so it crashes in [RtlpWaitForCriticalSection](http://source.winehq.org/git/wine.git/blob/a786dca935c3e9b3d85853db4b61700e590a1c8b:/dlls/ntdll/critsection.c#l448) as Wine is about to write to debug info about the mutex.

So it seems there is an additional problem here -- somehow `injectee.dll` is deadlocking.

**Comment by jrfonseca** [comment]
> So it seems there is an additional problem here -- somehow `injectee.dll` is deadlocking.

On 2nd thought, there's contention for the critical section, but not necessarily dead locking. WINE merely tries to log some debug info if any CS takes too long.

**Comment by EoD** [comment]
Thanks for the fast fix, I will test it as soon as I get access to the machine again.

**Comment by jrfonseca** [comment]
> From my perspective it seems like a bug in wine. Do you think I should report it upstream?

Yes, if you could report it on Wine bugzilla and add a comment to issue's URL it would be great.

**Comment by EoD** [comment]
Done: https://bugs.winehq.org/show_bug.cgi?id=39614
