### ISSUE TITLE
different order of calls, in trace and retrace (multithreaded application)

### ISSUE THREAD

**Issue by fred41** [apitrace/apitrace#401]
For multithreaded applications, new gl calls may arrive, complete and recorded, while previous calls (from diferent threads) are still processed (and unrecorded). 
Therefore the call records in file may be not sequenced correctly. 

The retracer replays the calls correct (via multiple threads), but in order of records.
Perhaps this may explain some strange results, while retracing multithreaded records.

Example:

2217 @0 glViewport(x = 0, y = 0, width = 1920, height = 1080)
2218 @0 glDepthRangef(n = 0, f = 1)
2219 @0 glDepthMask(flag = GL_TRUE)
2221 @1 glCreateBuffers(n = 1, buffers = &6)
2222 @1 glBindBuffer(target = GL_ARRAY_BUFFER, buffer = 6)
2223 @1 glBufferStorage(target = GL_ARRAY_BUFFER, size = 884736, data = NULL, flags = GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT)
2224 @1 glMapBufferRange(target = GL_ARRAY_BUFFER, offset = 0, length = 884736, access = GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT) = 0x7f0cc8d2f000
2225 @1 glGetError() = GL_NO_ERROR
2226 @1 glCreateBuffers(n = 1, buffers = &7)
2227 @1 glBindBuffer(target = GL_ELEMENT_ARRAY_BUFFER, buffer = 7)
2228 @1 glBindBuffer(target = GL_ELEMENT_ARRAY_BUFFER, buffer = 7)
2229 @1 glBufferStorage(target = GL_ELEMENT_ARRAY_BUFFER, size = 12288, data = NULL, flags = GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT)
2230 @1 glMapBufferRange(target = GL_ELEMENT_ARRAY_BUFFER, offset = 0, length = 12288, access = GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT) = 0x7f0cc8d2c000
2220 @0 glClear(mask = GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT | GL_COLOR_BUFFER_BIT)
2231 @0 glDepthMask(flag = GL_FALSE)

In this example, glClear (2220) is replayed past glMapBufferRange (2030), but was original occuring much earlier. (I can provide some traces from warthunder, a multithreaded freetoplay game.

Wouldn't be an option, to sort the calls by callnumbers, an wonderful improvement?

**Comment by jrfonseca** [comment]
> For multithreaded applications, new gl calls may arrive, complete and recorded, while previous calls (from diferent threads) are still processed (and unrecorded). 
> Therefore the call records in file may be not sequenced correctly.

This is more subtle than it looks.

When tracing, a global mutex is held temporarily while entering/leaving the function.  But no mutex is held  _inside_ the function.

The numbers associated with the calls are the sequence calls where _entered_.  But order control _left_ calls maybe different.

Imagine:

    enter function A
    enter function B 
    leave function B
    leave function A

what is the right order?  Should calls be ordered by entering order like

    1 call A
    2 call B

or by leaving order like

    1 call B
    2 call A

So, when dumping calls, apitrace the calls numbers you see are from the order calls were _entered_. 

But calls are listed and retrace by the orderer they _left_.  (Which is why sometimes calls are not monotonically increasing.) 

This was done this way because it requires less buffering.

We could do the opposite -- replay the calls by the order they were entered (ie accoding to the numbers you see associated with the casll) --, but that will required more buffering.

The reason we need buffering is that, in order to replay a call, in general it's not necessary to know just its inputs params -- it's important to know its output params too.

> I can provide some traces from warthunder, a multithreaded freetoplay game.

Yes please.

But above all, please explain why this matters.

Please realize there is no "right" or "wrong" here -- as it is technically impossibel to have call entering/leaving match precisely.  As I said above, the only choices is using the entering order, or the leaving order, but it is effectively impossible to have overlapping calls matching precisely. 

> Wouldn't be an option, to sort the calls by framenumbers, an wonderful improvement?

I don't understand what you mean by _framenumbers_.

**Comment by jrfonseca** [comment]
Just to make things clearer for you. back to your example above, the reason call 2020 was traced after call 2230 is because, call 2020 only _completed_ _after_ call 2230.

**Comment by jrfonseca** [comment]
BTW, another alternative would be to hold a mutex _during_ the calls, this would ensure calls enter/leaving events would pair up nicely.  But the drawback is that performance would suffer, so would the likelyhood of deadlocks, as some API call could block until some other call happened on another thread.

**Comment by fred41** [comment]
Thanks for your fast answer. I think i fully understand the reason for missordered records.

What i am trying to suggest, is something like a second pass, to sort the recorded data later by callnumbers. So we can have a more original ordering.

To make it more clear:
No we have: 'first completed' -> 'first replayed'.

With (second pass) sorting by callnumbers, we would have:
'First entered' -> 'First replayed'.

(Sorry for me simple english, i hope you can understand me :)

**Comment by fred41** [comment]
Meanwhile i think, the effect of sorting calls by callnumbers, is probably not worth the effort.
Let me just close this issue.

Thanks, and keep up your good work.
