### ISSUE TITLE
GPU over network

### ISSUE THREAD

**Issue by techtonik** [apitrace/apitrace#403]
My notebook GPU burned out, so I wonder if it is possible to use `apitrace` to redirect OpenGL calls to a capable device through the network, and render frames back to the calling application on the notebook?

**Comment by jrfonseca** [comment]
You want something like:

* http://www.virtualgl.org/
* http://chromium.sourceforge.net/

It would be possible in theory to use the apitrace's OpenGL API specifications to do something like this, but it is beyond the goal of apitrace project.

But to be honest, API remoting has _many_  problems. It is by far easier and more robust to use local GPU, and remote the rendered pixels.  Of course, this would not solve your problem since your GPU is busted.

Still, I reckon it would be several orders of magnitude cheaper to buy a new laptop, than to fund the development of what you ask.
