### ISSUE TITLE
D3D9 capture stops after app probing

### ISSUE THREAD

**Issue by iiv3** [apitrace/apitrace#432]
Some games create only a minimal trace (e.g. 2KB) , that doesn't contain any actual drawing.

All these games support more than one DirectX API. That's why I suspect the following happens:

The game starts D3D9, queries some stuff, closes it. Then does the same for D3D10, etc. After that it opens D3D9 again and uses it for real, but apitrace completely ignores it.

I just reproduced this with Crysis1 game. I also remember that it happens with STALKER games ( [Free Benchmark](http://downloads.guru3d.com/S.T.A.L.K.E.R-Call-of-Pripyat-benchmark-download-2433.html#download) ).

**Comment by jrfonseca** [comment]
I just downloaded the benchmark, not from that link, but http://cop.stalker-game.com/?page=benchmark 

And doing `apitrace trace -a d3d9 benchmark.exe` appears to be working fine.  It traces Benchmark.exe, then xrEngine.exe, and produces two traces Benchmark.trace and xrEngine.trace and the later as all the drawing.

Don't you get xrEngine.trace?

Are you running DebugView to see the apitrace messages?

**Comment by jrfonseca** [comment]
If you can confirm the issue is really there fell free to reopen.  Please always run DebugView when tracing on Windows to see important apitrace messages.

**Comment by iiv3** [comment]
It seem the issue is only present when using the wrapper library directly.
That is, placing the `d3d9.dll` wrapper into the game directory.

This is my favorite method for tracing games under wine, as it allows for global 'd3d9.dll native' override and avoid problems by calling trace on steam.

I'm mostly running traces under wine, and I think it does output to console all debug output.
Here is what I found in the logs. This block is the only mentioning apitrace.
```
apitrace: loaded into C:\Program Files\Call Of Pripyat Benchmark\bin_test\xrEngine.exe
fixme:ver:GetCurrentPackageId (0x32f3a8 (nil)): stub
apitrace: tracing to C:\Program Files\Call Of Pripyat Benchmark\xrEngine.1.trace
fixme:win:EnumDisplayDevicesW ((null),0,0x32f238,0x00000000), stub!
apitrace: unloaded from C:\Program Files\Call Of Pripyat Benchmark\bin_test\xrEngine.exe
```

**Comment by jrfonseca** [comment]
> It seem the issue is only present when using the wrapper library directly. [...] I'm mostly running traces under wine

@iiv3, please mention information like this from the start.  It makes the whole difference for this sort of issue.  I spent time trying to repro using the standard tracing method unnecessarily.

I repeat: whenever you file a bug, if you're doing things in any non-standard way (like using WINE or not using the `apitrace trace` CLI interface) make it well clear from the start.

It's in my interest to ensure apitrace works well (and particularly tracing), and I generally just like to help, but I have very little time to spare on apitrace, so I can't afford to spend it on wild goose chases. 

> xrEngine.1.trace

So you're saying that the `xrEngine*.trace` are almost empty?

It's highly likely that not using the standard DLL injection is indeed the root issue.  It's very easy to bypass the trace dll when using the DLL copy method -- all it takes is calling LoadLibrary() with the full `D3D9.DLL` -- something it's quite easy to do, even unintentionally, particularly because it's good security practice.

And there's nothing that can be done from DLL to prevent that.

My recommendation is that you figure a way to get DLL injection working again.  So you can resort to it when dropping the DLL in the app dir doesn't work.

Another solution is to actually modify WINE to be "apitrace aware", ie, have it so that anybody can easly obtain apitrace traces by modifying a WINE registry, pointing to the apitrace d3d9.dll path, and have wine itself injecting the DLL without requiring any hooking.

**Comment by iiv3** [comment]
The game definitely does not call LoadLibrary.
Wine actually allows tracing of dll loading. Here it is with apitrace debug output.
```
trace:loaddll:load_native_dll Loaded L"C:\\Program Files\\Call Of Pripyat Benchmark\\bin_test\\xrRender_R2.dll" at 0x21a0000: native
trace:loaddll:load_native_dll Loaded L"C:\\Program Files\\Call Of Pripyat Benchmark\\bin_test\\d3d9.dll" at 0x22a0000: native
apitrace: loaded into C:\Program Files\Call Of Pripyat Benchmark\bin_test\xrEngine.exe
fixme:ver:GetCurrentPackageId (0x32f3a8 (nil)): stub
apitrace: tracing to C:\Program Files\Call Of Pripyat Benchmark\xrEngine.trace
trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\opengl32.dll" at 0x7a820000: builtin
trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\wined3d.dll" at 0xf7130000: builtin
trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\d3d9.dll" at 0xf7270000: builtin
fixme:win:EnumDisplayDevicesW ((null),0,0x32f238,0x00000000), stub!
apitrace: unloaded from C:\Program Files\Call Of Pripyat Benchmark\bin_test\xrEngine.exe
trace:loaddll:free_modref Unloaded module L"C:\\Program Files\\Call Of Pripyat Benchmark\\bin_test\\d3d9.dll" : native
```
To me it looks like apitrace d3d9.dll wrapper is loaded, it starts and loads the system d3d9.dll (that loads `wined3d` that loads `opengl32`).
Then the Direct3D interface is closed and the d3d9.dll is unloaded.

Since d3d9 is not mentioned anymore (not loaded explicitly), the only way the program could continue to work is, if it uses the system d3d9.dll that have been loaded by apitrace.

Maybe, if wrapper/d3d9.dll unloads it's own system32/d3d9.dll, then the win(e) loader would try to load d3d9.dll again, hopefully from the game directory.

**Comment by jrfonseca** [comment]
> Maybe, if wrapper/d3d9.dll unloads it's own system32/d3d9.dll, then the win(e) loader would try to load d3d9.dll again, hopefully from the game directory.

You were right.  Should be fixed now.

> Also putting wrapper/d3d9.dll into game directory is what is described here

Right, that's inside the _Advanced command line usage_ > _Tracing manually_ sections.  It's not something I recommend, other than fallback if the standard way doesn't work.  And it's fine if you continue using it for Wine.  I just need to know that when there are tracing bugs.

**Comment by iiv3** [comment]
I can confirm that the issue if fixed.
Thank you.

As for the usage of the wrapper. To be honest I had no idea that invoking it though `apitrace trace` works. I've never tried it. I realized that `d3d9` wrapper usage is relevant after reading your comment.
My bad. Sorry.
