### ISSUE TITLE
Support reading float buffers and depth buffers for d3d 9

### ISSUE THREAD

**Issue by axeldavy** [apitrace/apitrace#436]
It would be great if we could see the content of float types textures and render targets (R16F, R32F).

Also it would be great to be able to see the depth buffer content. However it is likely more complicated: D32F_lockable seems widely supported, but there doesn't seem to be easy way to copy the depth buffer content to it.

EDIT:
Oh, I see you are using DXGI for a wide range of format support. Would you accept a pull request to support more formats without DXGI ?

**Comment by jrfonseca** [comment]
> Oh, I see you are using DXGI for a wide range of format support.

Right, through DirectXTex library, which is DXGI/D3D10+.

> Would you accept a pull request to support more formats without DXGI?

Probably adding hand-written code paths for some formats is unavoidable.  But I'd like to avoid reinventing the wheel as much as possible.

Could you propose a change that uses D3DX9's D3DXLoadSurfaceFromSurface to do the conversion when DXGI is not available?  I don't know about WINE's, but the real D3DX9 library supports lots of format conversion.

**Comment by jrfonseca** [comment]
> Also it would be great to be able to see the depth buffer content. However it is likely more complicated: D32F_lockable seems widely supported, but there doesn't seem to be easy way to copy the depth buffer content to it.

INTZ has the same bit pattern as D24S8, is widely supported, http://aras-p.info/texts/D3D9GPUHacks.html , and it can be locked (I just tried it on NVIDIA.)

However, the semantics of sampling from INTZ and D24S8 are different -- the former samples raw z values, where as the latter does implicit shadow compre.  And there's no practical way to blit from D24.

Microsoft PIX managed to get D3D9 depth values some how.  I don't know if it used some sort of backdoor to bypass the D3D9 runtime limations.

The only effective way to read an arbitrary depth-stencil buffer without abusing the D3D9 API is to:
* Create two `D3DFMT_R32F` surfaces with the same size as the depth stencil buffer, bind one as rendertarget, the other as sampler.
* For every bit in the depth buffer draw a textured quad, _bisecting_ the depth value using the depth test 
* First draw a quad with Red = Z = 0.5, ZFUNC=GREATEREQUAL.  This gets if MSB of the Z buffer
* Blit from render-target to texture
* Draw a quad with Red = 0.25, Z = 0.25 + sample(), and BLEND=ADD . This get the second MSB
* and so on.

A similar technique can be used for recovering the stencil values.

I never actually tried to implement above, but apart of some issues getting the LSB due to float vs UNORM24 rounding issues, it should work, and it should be fairly fast.

**Comment by axeldavy** [comment]
That indeed seems good technique to get the depth buffer content.

About wine D3DXLoadSurfaceFromSurface, I gave a short look, and it looks like it only supports converting to/from argb8888.
The formats I'd be very interested to have are R32F, R16F and the argb equivalents, but if you don't want to have them with handwritten code, I guess that's fine (I could still use my own branch).

**Comment by jrfonseca** [comment]
I just checked what PIX does: it's a bit less elaborate than what I proposed above, but simpler: 
it draws 256 quads, of linearly decreasing depth, each with a viewport MinZ, MaxZ = Z, where Z = 1.0 ... 2/255, 1/255, 0,  with ZFUNC=GREATER.  The Red is the same as Z, and theres' no bleding.  So all fragments start with red = 1, then get slowly replaced with lower values until the quad Z matches the fragment.

In short, PIX does a linear search of the depth values, where as my above scheme does a bisection.  PIX is simpler, but it really can only work if we only want 8 bits of depth stencil.


I'd happily accept a patch that does one or the other approach to get depth values.  I don't think I'll have the time or the need to implement it myself.


> About wine D3DXLoadSurfaceFromSurface, I gave a short look, and it looks like it only supports converting to/from argb8888. The formats I'd be very interested to have are R32F, R16F and the argb equivalents, but if you don't want to have them with handwritten code, I guess that's fine

I just wanted to avoid if possible.  I don't object.

On `retrace/glstate_formats.cpp` I had to do similar things for GL formats too.

**Comment by axeldavy** [comment]
For debugging, I'd need strictly more than 14 bits precision on the depth buffer (precision at the rasterizer stage), so the PIX way doesn't seem good enough.

When I get time, and once I manage to build apitrace exe on linux, I will give a try.

**Comment by jrfonseca** [comment]
> When I get time, and once I manage to build apitrace exe on linux, I will give a try.

Great.

Regarding Mingw crosscompilation, the instructions on https://github.com/apitrace/apitrace/blob/master/docs/INSTALL.markdown#mingw are quite terse.

To avoid getting lost I recommend following the Travis recipe:
* https://github.com/apitrace/apitrace/blob/master/.travis.yml
* https://travis-ci.org/apitrace/apitrace/jobs/117585403

One final remark: MinGW is not perfect.  For example, I just found out that MinGW is useless for DirectComposition, because some DirectComposition COM interfaces have overloaded methods, and it seems Mingw/GCC and MSVC order overloaded methods differently in the vtable...

**Comment by axeldavy** [comment]
Thanks, I managed to build with the instructions, thanks.

**Comment by siro20** [comment]
@jrfonseca: The delta sigma approach is not going to work, as you have to subtract the last tested value from depth, and that's not possible, is it ?
The only working way I see is to do a linear search, but for D3DFMT_D32 there are already 2^32 rendering passes necessary.

I implemented a technique to read the contents using RESZ hack, it's working on AMD and Intel and WINE.
I'll push it soon.

**Comment by jrfonseca** [comment]
> The delta sigma approach is not going to work, as you have to subtract the last tested value from depth, and that's not possible, is it ?

Yes, it's possible: you just bind the last tested value as a texture.  Or, if binding a texture both a rendertarget/texture causes problem, you bind a copy.   My comment https://github.com/apitrace/apitrace/issues/436#issuecomment-199503083 explains this in some detail.

> I implemented a technique to read the contents using RESZ hack, it's working on AMD and Intel and WINE.

It's a pity it doesn't work on NVIDIA.  But it's definitely an improvement, so I'm happy to take it.

**Comment by siro20** [comment]
This is implemented using d3d9 RESZ hack. However RESZ isn't supported by nvidia.

**Comment by jrfonseca** [comment]
I just found out there seems to be an official way to read depth/stencil surfaces from Vista onwards: https://msdn.microsoft.com/en-us/library/windows/desktop/bb219800.aspx#Reading_DepthStencil_Buffers

**Comment by siro20** [comment]
Yes, but all the restrictions apply:
1. You can't copy multisampled depth
2. You can't copy multiformat depth, like D24S8 or D24X8

As most games do multisampling and use D24S8/D24X8 it's pretty useless.

**Comment by jrfonseca** [comment]
> You can't copy multiformat depth, like D24S8 or D24X8

The impression I got is that one can: one can call `UpdateSurface` w/ `D3DFMT_S8_LOCKABLE` to get the stencil, w/ one of the `D3DFMT_D*_LOCKABLE` to get the depth, but maybe I misunderstood. Needs to be tried either way.

**Comment by jrfonseca** [comment]
FWIW I quickly tried to follow https://msdn.microsoft.com/en-us/library/windows/desktop/bb219800.aspx#Reading_DepthStencil_Buffers but couldn't make it work.  It doesn't seem to work as described at all.

I've pushed @siro20 PR. I couldn't get it to work correctly on HD 4000, so there might be still be some rough edges to iron out somewhere.

**Comment by axeldavy** [comment]
What did you try ? I'm curious.

If I understand the msdn link, it says to create a lockable identical depth buffer and use UpdateSurface to copy to the lockable buffer.
However UpdateSurface if for copying from SYSTEMMEM to DEFAULT... One should use GetRenderTargetData instead, but it isn't mentionned in the post. Also possibly it works only for d3d9Ex.

**Comment by jrfonseca** [comment]
@axeldavy I couldn't even create a SYSTEMMEM D32F_LOCKABLE offscreen plain surface, as documented.  I tried many variations of it, but the only one that worked was DEFAULT D32F_LOCKABLE, and UpdateSurface refused it.  I did try D3D9Ex device, but made no difference.  I did not try GetRenderTargetData.
