### ISSUE TITLE
Support for the Vulkan API

### ISSUE THREAD

**Issue by Amadiro** [apitrace/apitrace#439]
I have not yet seen any other feature-request pertaining this, so here it goes...

It'd be lovely if apitrace had Vulkan support!

**Comment by jrfonseca** [comment]
Vulkan API is a much _leaner_ API than OpenGL (it's easy to split traces and/or serialize all state), and the Vulkan ecosystem already equivalent tools:

* LunarG has vktrace/vkreplay:

  https://github.com/LunarG/VulkanTools/tree/master/vktrace
  http://lunarg.com/vulkan-sdk/faq/

  And at some point were working at some point in a so called [GLAVE debugger](http://www.dailymotion.com/video/x33yead).  It's not clear if vktrace/vkreplay is its [successor or not](https://www.reddit.com/r/vulkan/comments/468oz0/what_happened_to_the_glave_debugger/) 

* There's also [RenderDoc](https://github.com/baldurk/renderdoc)

I don't see advantages of duplicating or competing with the above efforts, specially since they are open-source, so if there's anything I'd like to do with Vulkan those tools don't support, or any bugs, it's probably easier to modify those tools, than to add Vulkan support to apitrace from scratch.

If anybody wants to support Vulkan in apitrace, I won't refuse patches, but I don't plan to work on it myself.

So I recommend you try the above tools.

**Comment by vinjn** [comment]
vktrace is successor of GLAVE.
