### ISSUE TITLE
wrappers/dlsym.cpp:107:44: error: 'basename' was not declared

### ISSUE THREAD

**Issue by c14006078** [apitrace/apitrace#470]
hello guys, I am trying to build apitrace on Android 5.1.1 and trying to trace app on emulator64-x86, but i fail.

here is my cmake command.
`$cmake .. 
-DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake 
-DANDROID_NDK=android-ndk-r10 
-DANDROID_ABI=x86_64 
-DANDROID_NATIVE_API_LEVEL=android-21 
-DANDROID_TOOLCHAIN_NAME=x86_64-4.9 
-DANDROID_API_LEVEL=21 
-DANDROID_STL=gnustl_shared 
-DANDROID_SDK=android-sdk-linux `

make error
`apitrace/wrappers/dlsym.cpp:107:44: error: 'basename' was not declared in this scope
     char *filename = basename(dupname.get());`

I can fix it by add `#include <libgen.h>`, but then I can't find the `make retraceAPK` command.

**Comment by jrfonseca** [comment]
> I can fix it by add `#include <libgen.h>`

The build failure was indeed due to lack of `libgen.h` include.

> but then I can't find the `make retraceAPK` command.

`make retraceAPK` is a command you have to type.  If the retraceAPK target doesn't exist for you, then there must be something from https://github.com/apitrace/apitrace/blob/master/docs/INSTALL.markdown#android instructions that was skipped.  It works for me FWIW.
