### ISSUE TITLE
replay the trace of DiRT Showdown show blank screen

### ISSUE THREAD

**Issue by jfactory07** [apitrace/apitrace#514]
when I trace DiRT Showdown, I didn't see any error message. But using glretrace to replay the trace I get blank screen.  You can get the trace file on:  http://u.163.com/Es4Pegup . please input  zOqHRiQF  to the text filed and then click the yellow button below the text filed.
 
I have tried to debug the issue, but I can't find any clue.
Thanks !

**Comment by jrfonseca** [comment]
The problem is that the application uses `GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT`.

You should have gotten a message like

    apitrace: warning: ...: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>

In short, this is a dup of issue https://github.com/apitrace/apitrace/issues/232 

Apitrace does not support this.  You need someway of telling the game not to use it  I'm afraid.

**Comment by jfactory07** [comment]
thanks for your reply!
