### ISSUE TITLE
Uncompressing the trace

### ISSUE THREAD

**Issue by Iman-sm** [apitrace/apitrace#518]
If we repack a trace file to zlib or brotli, and then uncompress the resulting file, what would be the format of the output file? at first i thought it would result in a text file, but after trying both compression formats, the resulting file was different from a text file (i was expecting to see the API commands in normal text format like when you dump a trace, but it was not). is there a way to convert a trace to text, modify the commands and then convert it back to trace (snappy) format again so we can see the result of our modification?

**Comment by jrfonseca** [comment]
> If we repack a trace file to zlib or brotli, and then uncompress the resulting file, what would be the format of the output file?

It would be precisely what's described in https://github.com/apitrace/apitrace/blob/master/docs/FORMAT.markdown

I already pointed it to you on https://github.com/apitrace/apitrace/issues/515#issuecomment-292809413

> is there a way to convert a trace to text, modify the commands and then convert it back to trace (snappy) format again so we can see the result of our modification?

No.  That functionality would indeed be convenient but it's not implemented.  It's not trivial to implement, because the binary apitrace format has sort of a builtin _schema_.
