### ISSUE TITLE
Query about error message

### ISSUE THREAD

**Issue by PhilPotter** [apitrace/apitrace#527]
Dear All,

I am attempting to investigate why my in-development OpenGL 4.x based PS1 emulator is randomly hardlocking my Linux machine, despite other 3D apps working just fine. I built from github and ran the apitrace tool and checked for leaks etc. but nothing came up. However, it repeatedly prints the error "shader compiler issue 1: Shader Stats: SGPRS: 24 VGPRS: 16 Code Size: 68 LDS: 0 Scratch: 0 Max Waves: 10 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0" with varying numbers of each value listed - always at the same GL calls in multiple traces. I am trying to decipher what the above means in case it is related to my problem, but I couldn't see it in the docs. Please could someone tell me? I have included a trace file to show what I mean. I am a newb to OpenGL so I am aware the fault is almost certainly my code and how I've written it, but I am none-the-less stuck :-) Thanks in advance for any help that can be provided.
[philpsx_2.11099279.trim.zip](https://github.com/apitrace/apitrace/files/1253947/philpsx_2.11099279.trim.zip)

Regards,
Phil

**Comment by jrfonseca** [comment]
Sorry, that message is not from apitrace tool itself, but from your OpenGL drivers.

I too am not sure what they mean.  But it seems like a harmless stats message.

apitrace tries to silence messages when it see many identical messages.  But unfortunately here every message is sliighly different due to the different state, so they don't get filtered.

When I replay your trace in my system, with Mesa drivers, I get

    6474 @2 glCompileShader(shader = 14)
    6474: warning: 0:31(26): warning: some implementations may not support implicit int -> uint conversions for `&' operators; consider casting explicitly for portability
    0:31(51): warning: some implementations may not support implicit int -> uint conversions for `&' operators; consider casting explicitly for portability
    0:31(78): warning: some implementations may not support implicit int -> uint conversions for `&' operators; consider casting explicitly for portability

Maybe it's worth addressing this.

At any rate, I'm afraid I don't have time to help people debugging their OpenGL apps.

Just a quick tip: try modify the code of your emulator to skip certain calls (e.g, draws with certain shaders), and keep skipping more and more stuff, until the problem goes away. Once you identify which shaders/draws are troublesome, you can them zoom in on them and see what's special about them, etc.

Good luck

**Comment by PhilPotter** [comment]
Ok thanks for your help, I'll try your suggestions :-)
