### ISSUE TITLE
Releases section outdated

### ISSUE THREAD

**Issue by Vpstr** [apitrace/apitrace#591]
Hello!
I'd like to know why you are not posting the new versions in the releases section. The binaries you provide are relatively fresh, while the releases section hasn't been updated since 2015. This looks kind of suspicious, like if you are hiding code modifications since that time. 
I also wonder why there are no binaries there. Many authors post binaries in the releases section, but you don't, instead providing only the latest binary elsewhere. Why?

**Comment by jrfonseca** [comment]
> I'd like to know why you are not posting the new versions in the releases section. 

Two reasons: https://github.com/apitrace/apitrace#status and because I prefer people to use master.

> The binaries you provide are relatively fresh, while the releases section hasn't been updated since 2015. This looks kind of suspicious, like if you are hiding code modifications since that time.

Not sure what you mean. It's open source, there's nothing hidden.

If somebody doesn't trust me, then they shouldn't any binaries.  Just build from source.  Binaries on freedesktop.org or github could be tampered by me just the same.

> I also wonder why there are no binaries there. Many authors post binaries in the releases section, but you don't, instead providing only the latest binary elsewhere. Why?

I don't want people to be using old binaries from old releases.  Because they'll run into issues/bugs/limitations that might be fixed on master.  And github doesn't provide a way to upload nightly releases, so I need to stash them somehere else.  (That said, development has been really slow.)

Using master is better than using any old release (unless one special requirements like OSes that have been abandoned, like Windows XP, Android.)

Honestly, I often feel tempted to stop doing releases altogether.

You might disagree with some of my answers, but I hope this at least answers your questions.  There's already a issue #570 asking for a new release.  So I'll be closing this soon.

**Comment by Vpstr** [comment]
I see your point.
> Not sure what you mean. It's open source, there's nothing hidden.
By this I mean that with releases I can always open the code state corresponding to each release and see modifications made since the previous one. This makes the development process more transparent for me, thus it's easier to audit it. Without releases it's more complicated, that's why I'm talking of hiding.
Tell me one more thing. It's written on the downloads page that MinGW binaries are also available, but I don't see them there. As Microsoft is a common enemy, I don't know what its enemy compiler pushes into the program at compilation, so I would like to have an access to an alternative version.
And can I attach these labels to an issue myself?

**Comment by jrfonseca** [comment]
Pushed a new release now.  So closing this issue now.

I've stopped making MinGW releases, because GNU C++ compiler is broken -- it gets confused with COM interfaces with overloaded methods.  I still use MinGW for development (for convenience), but I don't recommend using for production.

Regarding the labels, no, labels can only be attached by project members.
