### ISSUE TITLE
qapitrace memory usage explodes when showing call inside a frame.

### ISSUE THREAD

**Issue by gregory38** [apitrace/apitrace#81]
Hello,

Here a small trace of my application (emulation of the GPU of PS2):
https://docs.google.com/open?id=0BzftmrM8nnSobDk3eU5IY0pXTHM

When I click on the plus of the latest frame to see the different call. I reach 3.6GB! I used the 32bits version of apitrace (on an amd64 system because my application is 32bits only) so at 4GB qapitrace die.

My qt version is 4.8.1-1

Gregory

**Comment by jrfonseca** [comment]
Sorry, I totally dropped the ball on this issue.  I must have forgotten to star the email, thenit  totally dropped out of my radar.

Recently I ended up yanking out ApiTraceEnumSignature in 446ca50d78d519230060d60c7179347ffb23de0c .  The ability to edit enums had also been gone for a while, due to other bugs.

As I said on 446ca50d78d519230060d60c7179347ffb23de0c I believe that instead of converting every `trace_model.hpp` object into a QVariant is it preferable for the GUI to hold on to the `trace_model.hpp` objects themselves, and only produce Qt objects for the derived state it needs for fast render/search.
