### ISSUE TITLE
Apitrace  trace replay too fast

### ISSUE THREAD

**Issue by neofeo** [apitrace/apitrace#812]
Hi, I was trying to get a trace from an opengl linux game and the game has a lot of dropping frames on my platform, that's  why I wanted an apitrace the thing is... the replay goes tooo fast and not on real time, making the game too looks smooth  while it's  not.

Alternatively, I would like if at least galliumhud can be added to apitrace so that could at least show the real performance. 

I am testing latest main apitrace from a day ago.

Thanks on advance.

**Comment by jrfonseca** [comment]
apitrace might be wrong tool.

If the game drops frames, then dropped frames won't be recorded by apitrace.  Furthermore, due to the overhead of writing trace to disk when recording, more frames are likely to be dropped.

The fact that replaying the frames is so quick means the recorded frames are _not_ the bottleneck.

In short, even if apitrace replayed the frames very slowly, it would not help you or anybody to figure out why the game was slow.  From what you describe, it might not even be graphics related (e.g, it could be network or disk related.)

If this is a Linux game, I recommend using general profiling tools like [Linux perf](https://perf.wiki.kernel.org/index.php/Main_Page).

I hope this helps.
