### ISSUE TITLE
Request: provide artifacts for pull requests..

### ISSUE THREAD

**Issue by oscarbg** [apitrace/apitrace#822]
Hi,
at least Windows and/or Linux would be nice..
I think it's a reasonable request since the project has low volume of PRs and they are already being built with Actions..
in fact interested to test a fix for a bug I submitted (https://github.com/apitrace/apitrace/actions/runs/2978799525).
seeing how commits to master branch have at least ubuntu artifacts 
https://github.com/apitrace/apitrace/actions/runs/2689457557
would be nice to have similarly..

thanks..

**Comment by jrfonseca** [comment]
In such circumstances, I think the idea would actually to enable artifacts on forks.

The workflow would be as follows: one would fork apitrace onto ones github personal space, push a fix, test the artifacts, and then when test concluded, one would submit the PR.

This is even more important because GitHub actions don't run automatically for PRs for new contributors -- one needs to approve.

I'll enable it shortly.

**Comment by oscarbg** [comment]
thanks for doing it, and for the explanation, makes sense..
